version: "3.3"
services:
    cmp-coming-soon:
        build: .
        restart: always
        image: cmp-coming-soon:latest
        container_name: cmp-coming-soon
        volumes: 
             - appData001:/usr/share/nginx/html
        networks:
            - web
        labels:
            - traefik.enable=true
            - traefik.docker.network=web
            - traefik.frontend.rule=Host:eglisecmp.com
            - traefik.port=80
            - "traefik.frontend.passHostHeader=true"    

networks:
    web:
        external:
            name: web
volumes:
      appData001 : {}